name: train-clustered
channels:
    - conda-forge
dependencies:
    # Models
    - molvs==0.1.1
    - rdkit==2024.03.3
    - scikit-learn==1.5.0
    - scikit-learn-intelex==2024.3.0
    - xgboost==2.0.3
    - py4j==0.10.9.7
    - dask==2024.5.2
    - dask-jobqueue==0.8.5
    # Development
    - pyright==1.1.366
    - ruff==0.4.8
    - jupyterlab==4.2.2
    - pip:dask_labextension==7.0.0
